"""add definition column

Revision ID: eae6f1c59412
Revises: 16788108bc25
Create Date: 2026-09-22 16:10:32.586247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eae6f1c59412'
down_revision: Union[str, Sequence[str], None] = '16788108bc25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_schedules_id'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_next_run_at'), table_name='schedules')
    op.drop_table('schedules')
    op.drop_index(op.f('ix_worker_heartbeats_id'), table_name='worker_heartbeats')
    op.drop_index(op.f('ix_worker_heartbeats_last_heartbeat'), table_name='worker_heartbeats')
    op.drop_table('worker_heartbeats')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_workflow_tasks_id'), table_name='workflow_tasks')
    op.drop_index(op.f('ix_workflow_tasks_priority'), table_name='workflow_tasks')
    op.drop_index(op.f('ix_workflow_tasks_status'), table_name='workflow_tasks')
    op.drop_table('workflow_tasks')
    op.drop_index(op.f('ix_events_created_at'), table_name='events')
    op.drop_index(op.f('ix_events_event_type'), table_name='events')
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_dead_letter_tasks_id'), table_name='dead_letter_tasks')
    op.drop_table('dead_letter_tasks')
    op.drop_index(op.f('ix_task_attempts_id'), table_name='task_attempts')
    op.drop_table('task_attempts')
    op.drop_table('workers')
    op.drop_table('idempotency_keys')
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('ADMIN', 'OPERATOR', 'DEVELOPER', 'VIEWER', name='userrole'),
               type_=sa.String(),
               nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.add_column('workflow_runs', sa.Column('workflow_id', sa.Integer(), nullable=False))
    op.add_column('workflow_runs', sa.Column('version_id', sa.Integer(), nullable=False))
    op.alter_column('workflow_runs', 'status',
               existing_type=postgresql.ENUM('CREATED', 'QUEUED', 'RUNNING', 'PAUSED', 'COMPLETED', 'FAILED', 'CANCELLED', 'PARTIAL_FAILURE', name='workflowstatus'),
               type_=sa.String(),
               nullable=True)
    op.alter_column('workflow_runs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('workflow_runs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index(op.f('ix_workflow_runs_status'), table_name='workflow_runs')
    op.drop_constraint(op.f('workflow_runs_workflow_version_id_fkey'), 'workflow_runs', type_='foreignkey')
    op.drop_constraint(op.f('workflow_runs_triggered_by_id_fkey'), 'workflow_runs', type_='foreignkey')
    op.create_foreign_key(None, 'workflow_runs', 'workflows', ['workflow_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'workflow_runs', 'workflow_versions', ['version_id'], ['id'])
    op.drop_column('workflow_runs', 'workflow_version_id')
    op.drop_column('workflow_runs', 'triggered_by_id')
    op.add_column('workflow_versions', sa.Column('definition', sa.JSON(), nullable=False))
    op.add_column('workflow_versions', sa.Column('created_by_id', sa.Integer(), nullable=False))
    op.alter_column('workflow_versions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_constraint(op.f('uq_workflow_version'), 'workflow_versions', type_='unique')
    op.create_foreign_key(None, 'workflow_versions', 'users', ['created_by_id'], ['id'])
    op.drop_column('workflow_versions', 'definition_json')
    op.alter_column('workflows', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workflows', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.add_column('workflow_versions', sa.Column('definition_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'workflow_versions', type_='foreignkey')
    op.create_unique_constraint(op.f('uq_workflow_version'), 'workflow_versions', ['workflow_id', 'version_number'], postgresql_nulls_not_distinct=False)
    op.alter_column('workflow_versions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('workflow_versions', 'created_by_id')
    op.drop_column('workflow_versions', 'definition')
    op.add_column('workflow_runs', sa.Column('triggered_by_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('workflow_runs', sa.Column('workflow_version_id', sa.INTEGER(), autoincrement=False, nullable=False))
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'workflow_runs', type_='foreignkey')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'workflow_runs', type_='foreignkey')
    op.create_foreign_key(op.f('workflow_runs_triggered_by_id_fkey'), 'workflow_runs', 'users', ['triggered_by_id'], ['id'])
    op.create_foreign_key(op.f('workflow_runs_workflow_version_id_fkey'), 'workflow_runs', 'workflow_versions', ['workflow_version_id'], ['id'])
    op.create_index(op.f('ix_workflow_runs_status'), 'workflow_runs', ['status'], unique=False)
    op.alter_column('workflow_runs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('workflow_runs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('workflow_runs', 'status',
               existing_type=sa.String(),
               type_=postgresql.ENUM('CREATED', 'QUEUED', 'RUNNING', 'PAUSED', 'COMPLETED', 'FAILED', 'CANCELLED', 'PARTIAL_FAILURE', name='workflowstatus'),
               nullable=False)
    op.drop_column('workflow_runs', 'version_id')
    op.drop_column('workflow_runs', 'workflow_id')
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.String(),
               type_=postgresql.ENUM('ADMIN', 'OPERATOR', 'DEVELOPER', 'VIEWER', name='userrole'),
               nullable=False)
    op.create_table('idempotency_keys',
    sa.Column('key', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('response_payload', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('idempotency_keys_pkey'))
    )
    op.create_table('workers',
    sa.Column('id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('registered_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('workers_pkey'))
    )
    op.create_table('task_attempts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('attempt_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('worker_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('finished_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['workflow_tasks.id'], name=op.f('task_attempts_task_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('task_attempts_pkey'))
    )
    op.create_index(op.f('ix_task_attempts_id'), 'task_attempts', ['id'], unique=False)
    op.create_table('dead_letter_tasks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('failure_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('moved_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['workflow_tasks.id'], name=op.f('dead_letter_tasks_task_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('dead_letter_tasks_pkey'))
    )
    op.create_index(op.f('ix_dead_letter_tasks_id'), 'dead_letter_tasks', ['id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('workflow_run_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('payload', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['workflow_run_id'], ['workflow_runs.id'], name=op.f('events_workflow_run_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('events_pkey'))
    )
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    op.create_index(op.f('ix_events_event_type'), 'events', ['event_type'], unique=False)
    op.create_index(op.f('ix_events_created_at'), 'events', ['created_at'], unique=False)
    op.create_table('workflow_tasks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('workflow_run_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('task_key', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('task_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'QUEUED', 'RUNNING', 'SUCCESS', 'FAILED', 'RETRYING', 'CANCELLED', 'TIMED_OUT', 'SKIPPED', name='taskstatus'), autoincrement=False, nullable=False),
    sa.Column('priority', postgresql.ENUM('CRITICAL', 'HIGH', 'NORMAL', 'LOW', name='taskpriority'), autoincrement=False, nullable=False),
    sa.Column('config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('dependencies', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('retry_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('max_retries', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['workflow_run_id'], ['workflow_runs.id'], name=op.f('workflow_tasks_workflow_run_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('workflow_tasks_pkey'))
    )
    op.create_index(op.f('ix_workflow_tasks_status'), 'workflow_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_workflow_tasks_priority'), 'workflow_tasks', ['priority'], unique=False)
    op.create_index(op.f('ix_workflow_tasks_id'), 'workflow_tasks', ['id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('actor_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('resource_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('resource_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('metadata_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('audit_logs_actor_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('audit_logs_pkey'))
    )
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_table('worker_heartbeats',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('worker_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('last_heartbeat', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], name=op.f('worker_heartbeats_worker_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('worker_heartbeats_pkey'))
    )
    op.create_index(op.f('ix_worker_heartbeats_last_heartbeat'), 'worker_heartbeats', ['last_heartbeat'], unique=False)
    op.create_index(op.f('ix_worker_heartbeats_id'), 'worker_heartbeats', ['id'], unique=False)
    op.create_table('schedules',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('workflow_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cron_expression', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('last_run_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('next_run_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], name=op.f('schedules_workflow_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('schedules_pkey'))
    )
    op.create_index(op.f('ix_schedules_next_run_at'), 'schedules', ['next_run_at'], unique=False)
    op.create_index(op.f('ix_schedules_id'), 'schedules', ['id'], unique=False)
    # ### end Alembic commands ###
